apiVersion: secret.com/v1alpha1
kind: Application
metadata:
  name: xxxxxxx-dev
spec:
  port: 3000
  envFrom:
    - secretRef:
        name: xxxxxx-dev
  livenessProbe:
    httpGet:
      path: /api/health/ping
      port: 3000
    periodSeconds: 30
    timeoutSeconds: 30
  readinessProbe:
    httpGet:
      path: /api/health/ping
      port: 3000
    periodSeconds: 30
    timeoutSeconds: 30
  replicas: 1
  quota: q512mb